In [110]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [112]:
# Load the dataset
data=pd.read_csv("C:\\Users\\dheni\\Downloads\\DS Assignments\\18.Neural networks\\Alphabets_data.csv")
data

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6   
1          I     5    12      3       7      2    10     5      5      4   
2          D     4    11      6       8      6    10     6      2      6   
3          N     7    11      6       6      3     5     9      4      6   
4          G     2     1      3       1      1     8     6      6      6   
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          6      10       8      0       8      0       8  
1         13       3       9      2       8      4      10  
2         10       3       7      3       7      3       9  
3          4       4      10      6      10      2       8  
4          6       5       9      1       7      5      10  
...      ...     ...     ...    ...     ...    ...     ...  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  

[20000 rows x 17 columns]

In [114]:
# Summarize key features
print("Number of samples:", data.shape[0])
print("Number of features:", data.shape[1] - 1)  # Excluding the letter column
print("Classes:", data['letter'].unique())

Number of samples: 20000
Number of features: 16
Classes: ['T' 'I' 'D' 'N' 'G' 'S' 'B' 'A' 'J' 'M' 'X' 'O' 'R' 'F' 'C' 'H' 'W' 'L'
 'P' 'E' 'V' 'Y' 'Q' 'U' 'K' 'Z']


In [116]:
# Import libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [118]:
# Missing values
data.isnull().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [120]:
# Normalize features
x = data.drop('letter', axis=1)
y = data['letter']

In [122]:
# Encode the labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_encoded

array([19,  8,  3, ..., 19, 18,  0])

In [124]:
# Scaling the data
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[-1.0576983 ,  0.29187713, -1.05327668, ..., -0.21908163,
        -1.4381527 ,  0.12291107],
       [ 0.51038497,  1.5023577 , -1.05327668, ..., -0.21908163,
         0.12008142,  1.35944092],
       [-0.01230945,  1.19973756,  0.43590966, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       ...,
       [ 1.03307939,  0.59449727,  0.43590966, ...,  2.36709667,
        -0.65903564, -2.35014863],
       [-1.0576983 , -1.22122359, -0.55688123, ...,  0.42746295,
         0.50963994,  0.12291107],
       [-0.01230945,  0.59449727,  0.43590966, ..., -0.8656262 ,
        -0.65903564,  0.12291107]])

In [126]:
# Split the dataset into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)

In [128]:
# Splitting size
print(x_train.shape)
print(x_test.shape)

(16000, 16)
(4000, 16)


In [130]:
# Import libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [132]:
# Import library
import warnings
warnings.filterwarnings('ignore')

In [134]:
# Construct a basic ANN model
model = keras.Sequential()
model.add(layers.InputLayer(input_shape=(x_train.shape[1],)))

In [136]:
# Adding one hidden layer with 32 neurons and ReLU activation
model.add(layers.Dense(32, activation='relu'))

In [138]:
# Output layer for multi-class classification
model.add(layers.Dense(len(np.unique(y_encoded)), activation='softmax'))  # Assuming classification of multiple alphabets

In [140]:
# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [142]:
# Train the model
history = model.fit(x_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.1935 - loss: 2.9114 - val_accuracy: 0.5291 - val_loss: 1.7865
Epoch 2/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5766 - loss: 1.6003 - val_accuracy: 0.6672 - val_loss: 1.2527
Epoch 3/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6890 - loss: 1.1419 - val_accuracy: 0.7194 - val_loss: 1.0443
Epoch 4/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7355 - loss: 0.9697 - val_accuracy: 0.7428 - val_loss: 0.9356
Epoch 5/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7531 - loss: 0.8832 - val_accuracy: 0.7616 - val_loss: 0.8545
Epoch 6/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7778 - loss: 0.7950 - val_accuracy: 0.7725 - val_loss: 0.7999
Epoch 7/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7877 - loss: 0.7478 - val_accuracy: 0.7869 - val_loss: 0.7584
Epoch 8/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7990 - loss: 0.7104 - val_accuracy: 0.

In [144]:
# Make predictions on the test set
y_pred = model.predict(x_test)
y_pred

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


array([[1.09278858e-06, 1.47986452e-06, 2.87022260e-07, ...,
        9.26351428e-01, 5.35101456e-08, 6.30767494e-02],
       [1.69505458e-02, 1.18491962e-03, 2.39773989e-02, ...,
        5.80601282e-02, 2.56141904e-03, 3.59502519e-06],
       [9.99989510e-01, 5.20072046e-15, 2.19764549e-12, ...,
        4.32815339e-10, 1.29719776e-13, 1.26630761e-09],
       ...,
       [4.20363371e-08, 2.19108655e-11, 1.01710128e-07, ...,
        5.55640838e-07, 7.02096088e-08, 1.03564609e-14],
       [1.61696167e-03, 9.89067104e-08, 1.33221999e-06, ...,
        9.15803481e-04, 9.13760781e-01, 1.18123069e-02],
       [3.18289786e-08, 2.66773433e-14, 6.03599852e-13, ...,
        1.10919005e-04, 9.99308944e-01, 7.49807792e-17]], dtype=float32)

In [146]:
# Make Predictions on classes
y_pred_classes = np.argmax(y_pred, axis=1)
y_pred_classes

array([23, 11,  0, ..., 16, 24, 24], dtype=int64)

In [148]:
# Import library
from sklearn.metrics import classification_report, accuracy_score

In [150]:
# Classification report
report = classification_report(y_test, y_pred_classes)
print(report)

              precision    recall  f1-score   support

           0       0.92      0.91      0.91       149
           1       0.79      0.86      0.82       153
           2       0.89      0.88      0.88       137
           3       0.85      0.86      0.85       156
           4       0.85      0.87      0.86       141
           5       0.86      0.87      0.87       140
           6       0.85      0.82      0.83       160
           7       0.77      0.69      0.73       144
           8       0.96      0.92      0.94       146
           9       0.92      0.92      0.92       149
          10       0.77      0.85      0.81       130
          11       0.93      0.94      0.94       155
          12       0.89      0.94      0.92       168
          13       0.91      0.88      0.90       151
          14       0.90      0.86      0.88       145
          15       0.96      0.87      0.91       173
          16       0.94      0.95      0.94       166
          17       0.77    

I used Randomforestclassifier due to KerasClassifier is not supporting and it is showing module not found errors even after installing different versions of tensorflow and keras. So I used different classifier which can satisy the tasks.

In [152]:
# Import libraries
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [154]:
# Create the Random Forest classifier
rf_classifier = RandomForestClassifier(random_state=42)
# Train the model
rf_classifier.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [156]:
# Make predictions on the test set
y_pred = rf_classifier.predict(x_test)
y_pred

array([19, 11,  0, ..., 16, 24, 24])

In [158]:
# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")

Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       149
           1       0.89      0.97      0.93       153
           2       0.99      0.92      0.95       137
           3       0.90      0.97      0.94       156
           4       0.90      0.99      0.95       141
           5       0.92      0.96      0.94       140
           6       0.97      0.96      0.97       160
           7       0.96      0.89      0.92       144
           8       0.99      0.92      0.96       146
           9       0.95      0.98      0.97       149
          10       0.94      0.90      0.92       130
          11       0.99      0.97      0.98       155
          12       0.97      0.99      0.98       168
          13       0.98      0.92      0.95       151
          14       0.95      0.95      0.95       145
          15       0.98      0.95      0.96       173
          16       0.96      0.97      0.96       166
    

In [160]:
# Define the hyperparameter grid
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]}

In [162]:
# Create a Random Forest model for hyperparameter tuning
rf_model = RandomForestClassifier(random_state=42)
rf_model

RandomForestClassifier(random_state=42)

In [164]:
# Perform grid search
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, scoring='accuracy', cv=3)
grid_search

GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [None, 10, 20],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 100]},
             scoring='accuracy')

In [166]:
# Grid result
grid_result = grid_search.fit(x_train, y_train)
grid_result

GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [None, 10, 20],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 100]},
             scoring='accuracy')

In [169]:
# Summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: 0.951188 using {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}


In [171]:
# Get the best model
best_model = grid_result.best_estimator_
best_model

RandomForestClassifier(random_state=42)

In [173]:
# Make predictions with the best model
y_pred_best = best_model.predict(x_test)
y_pred_best

array([19, 11,  0, ..., 16, 24, 24])

In [175]:
# Evaluate the best model
print("Best Model Classification Report:")
print(classification_report(y_test, y_pred_best))
print(f"Best Model Accuracy: {accuracy_score(y_test, y_pred_best)}")

Best Model Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       149
           1       0.89      0.97      0.93       153
           2       0.99      0.92      0.95       137
           3       0.90      0.97      0.94       156
           4       0.90      0.99      0.95       141
           5       0.92      0.96      0.94       140
           6       0.97      0.96      0.97       160
           7       0.96      0.89      0.92       144
           8       0.99      0.92      0.96       146
           9       0.95      0.98      0.97       149
          10       0.94      0.90      0.92       130
          11       0.99      0.97      0.98       155
          12       0.97      0.99      0.98       168
          13       0.98      0.92      0.95       151
          14       0.95      0.95      0.95       145
          15       0.98      0.95      0.96       173
          16       0.96      0.97      0.96    